######################################################################
##  Stuff that needs to happen at 05:50am.
######################################################################

- alias: 'Timed 550'
  id: 7bf33e23-021c-4e11-946b-b052b81fd2bc
  trigger:
    - platform: time
      at: '05:50:00'

  condition:
    - condition: state
      entity_id: group.family
      state: home
    - condition: state
      entity_id: input_boolean.school_mode
      state: 'on'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  action:
    - service: homeassistant.turn_on
      entity_id:
        - light.dining_room_lights
        - light.fridge
        - light.k2
        - light.k3
        - light.k5
