######################################################################
##  Stuff that needs to happen at 08:30am.
######################################################################

- alias: 'Kids left for the day'
  id: 7cc9a7d6-8918-4a4a-98e7-a46abc9df4f1
  trigger:
    - platform: time
      at: '08:30:00'

  condition:
    - condition: state
      entity_id: group.family
      state: home
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.school_mode
      state: 'on'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - wait_template: >-
       {{ is_state('group.garage_doors', 'open') }}
    - delay: 00:03:00
    - service: light.turn_off
      entity_id: all
