###################################
##  Start Up Section
###################################

- alias: Startup Notification and Shut startup lights

  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: script.notify_engine
      data_template:
        title: 'Home Assistant StartUp'
        value1: 'Home Assistant is Up and Running!'
        who: 'carlo'
        apns_id: 'information'

    - service: light.turn_off
      entity_id: light.hallway_lights

    - service: mqtt.publish
      data:
        topic: "garadget/GSmall/command"
        payload: "get-status"

    - service: mqtt.publish
      data:
        topic: "garadget/GLarge/command"
        payload: "get-status"

    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'

    - service: notify.alexa_media
      data:
        target:
          - media_player.office
        title: "Home Assistant Restarted"
        data:
          type: announce
          #method: all
        message: "Home Assistant has been restarted."
