###################################
##  Sunrise and Sunset stuff
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
###################################

- alias: 'Sunset Stuff on'
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:20:00"
  action:
    - delay: '00:{{ (range(1, 20)|random|int) }}:00'
    - service: script.tweet_engine_image
      data_template:
        tweet: >-
          {{ [
          "Right before sunset, I turn on the outdoor lights.",
          "The sun is offical down. Exterior Cameras are now motion acivated.",
          "Since it gets dark around sunset, I will turn on the landscaping lights.",
          "The sun has been ushered off the stage. Activate the perimiter cameras.",
          "When the Sun goes down, I help out by turning on the outside lights. It is the little things in life.",
          "Time to turn on the Landscaping lights.",
          "Daytime is over, Time to turn on the exterior lights.",
          "Once the Sun goes down, we turn on the exterior lights.",
          "Switching to night mode!",
          "Since it is sunset, I will turn on the exterior lights."
          ] | random + [
          " #Sunset",
          " #HomeAutomation",
          " #AccentLighting",
          " (https://www.vcloudinfo.com/2017/08/diy-outdoor-smart-home-led-strips.html)",
          " (https://youtu.be/FcBVu_yk2iY)",
          " (https://www.vcloudinfo.com/2018/09/unboxing-philips-hue-calla-landscape.html)"
          ] | random }}
        image: >-
          {{ [
          "/config/www/custom_ui/floorplan/images/branding/light.png",
          "/config/www/custom_ui/floorplan/images/branding/light2.png",
          "/config/www/custom_ui/floorplan/images/branding/light3.png",
          "/config/www/custom_ui/floorplan/images/branding/light4.png",
          "/config/www/custom_ui/floorplan/images/branding/landscape_light.png",
          "/config/www/custom_ui/floorplan/images/branding/sunset.png"
          ] | random }}
    - service: script.speech_engine
      data:
        call_dark_outside: 1
        call_window_check: 1
    - service: homeassistant.turn_on
      entity_id:
        - switch.front_landscaping
        - light.bedroom
    - service: script.monthly_color_scene
    - service: light.turn_on
      entity_id:
        - light.outdoor_bathroom
      data_template:
        brightness: >
          {% if states.group.family.state == 'home' -%}
          10
          {% else %}
          200
          {% endif %}
    - wait_template: >-
       {{ states.group.family.state == 'home' }}
    - service: switch.turn_on
      entity_id:
       - group.master_bathroom_accents
       - switch.back_landscaping
       - switch.front_door_outlet
       - switch.foyer_outlet
    - service: light.turn_on
      entity_id:
       - group.living_room_accents
    - wait_template: >-
       {{ is_state('group.garage_doors', 'closed') }}
    - wait_template: >-
       {{ is_state('group.entry_points', 'off') }}
    - service: script.speech_engine
      data:
       call_garage_check: 1
       call_window_check: 1
