# https://github.com/marketplace/actions/label-commenter

labels:
  - name: "integration: utility_meter"
    labeled:
      issue:
        body: "#HomeAssistant ```utility_meter``` integration documentation - https://www.home-assistant.io/integrations/utility_meter/"

  - name: "integration: alert"
    labeled:
      issue:
        body: "#HomeAssistant ```alert``` integration documentation - https://www.home-assistant.io/integrations/alert/"
        
  - name: "integration: input_number"
    labeled:
      issue:
        body: "#HomeAssistant ```input_number``` integration documentation - https://www.home-assistant.io/integrations/input_number/"

  - name: "integration: input_text"
    labeled:
      issue:
        body: "#HomeAssistant ```input_text``` integration documentation - https://www.home-assistant.io/integrations/input_text/"

  - name: "integration: counter"
    labeled:
      issue:
        body: "#HomeAssistant ```counter``` integration documentation - https://www.home-assistant.io/integrations/counter/"
        
  - name: "integration: input_boolean"
    labeled:
      issue:
        body: "#HomeAssistant ```input_boolean``` integration documentation - https://www.home-assistant.io/integrations/input_boolean/"

  - name: "integration: binary_sensor"
    labeled:
      issue:
        body: "#HomeAssistant ```binary_sensor``` integration documentation - https://www.home-assistant.io/integrations/binary_sensor/ and https://www.home-assistant.io/integrations/binary_sensor.template/"
        
  - name: "integration: input_datetime"
    labeled:
      issue:
        body: "#HomeAssistant ```input_datetime``` integration documentation - https://www.home-assistant.io/integrations/input_datetime/"
        
  - name: "integration: input_select"
    labeled:
      issue:
        body: "#HomeAssistant ```input_select``` integration documentation - https://www.home-assistant.io/integrations/input_select/"

  - name: "integration: person"
    labeled:
      issue:
        body: "#HomeAssistant ```person``` integration documentation - https://www.home-assistant.io/integrations/person/"
        
  - name: "integration: timer"
    labeled:
      issue:
        body: "#HomeAssistant ```timer``` integration documentation - https://www.home-assistant.io/integrations/timer/"
        
  - name: "integration: sensor_template"
    labeled:
      issue:
        body: "#HomeAssistant ```sensor``` integration documentation - https://www.home-assistant.io/integrations/template/"
        
  - name: "core: lovelace"
    labeled:
      issue:
        body: "#HomeAssistant ```lovelace``` documentation - https://www.home-assistant.io/lovelace/"        
        
  - name: "lovelace: dashboards"
    labeled:
      issue:
        body: "#HomeAssistant ```lovelace dashbaords``` documentation - https://www.home-assistant.io/lovelace/dashboards-and-views/"           
        
  - name: "lovelace: cards"
    labeled:
      issue:
        body: "#HomeAssistant ```lovelace cards``` documentation - https://www.home-assistant.io/lovelace/entity/"     
