#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# Neato Support for D7 Connected Botvac - control my [Neato Vacuum](http://amzn.to/2kqnnqu) with Home Assistant.
#-------------------------------------------
homeassistant:
  customize_glob:
    "*.arris_tg1682g_router*":
      homebridge_hidden: True
      hidden: False
#-------------------------------------------

group:
  router:
    name: Router Stats
    control: hidden
    entities:
      - sensor.arris_tg1682g_router_bytes_received
      - sensor.arris_tg1682g_router_bytes_sent
      - sensor.arris_tg1682g_router_kbytesec_received
      - sensor.arris_tg1682g_router_kbytesec_sent
      - sensor.arris_tg1682g_router_packets_received
      - sensor.arris_tg1682g_router_packets_sent
      - sensor.arris_tg1682g_router_packetssec_received
      - sensor.arris_tg1682g_router_packetssec_sent

#############################################################################
###  Automations - Alerts related to the JuiceBox (http://amzn.to/2AZVQ37)
##############################################################################
  #
  # - alias: 'JuiceBox AMP Alert!'
  #   initial_state: 'on'
  #   trigger:
  #     - platform: numeric_state
  #       entity_id: sensor.carlojuice_amps
  #       above: 24
  #       for:
  #         minutes: 2
  #   action:
  #     - service: input_boolean.turn_on
  #       entity_id: input_boolean.alert_mode
  #
  #     - service: script.notify_engine
  #       data_template:
  #         value1: "The Juice Box Charger is pulling {{ states('sensor.carlojuice_amps') }} AMPs.  This is above the safety mark of 30.  Please unplug charger immediately."
  #         who: 'parents'
  #
  #     - service: script.speech_engine
  #       data_template:
  #         value1: "The Juice Box Charger is pulling {{ states('sensor.carlojuice_amps') }} AMPs.  This is above the safety mark of 30.  Please unplug charger immediately."
