#-------------------------------------------
#  C by GE Lights - https://amzn.to/30w3UWy
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#  These lights are only accessable via Alexa so going to use special Routines to control them. (Loosely)
# https://github.com/CCOSTAN/Home-AssistantConfig/issues/812
#-------------------------------------------

##################################################
## Scripts
## Called in the AWAY script to shut all devices down.
##################################################

script:
  paige_lights_off:
    alias: 'Paige ALL Lights Off'
    sequence:
      - service: media_player.play_media
        data:
          entity_id: media_player.paige_room
          media_content_id: paigelightoff
          media_content_type: routine

  paige_lights_on:
    alias: 'Paige Lights On - Just Overhead'
    sequence:
      - service: media_player.play_media
        data:
          entity_id: media_player.paige_room
          media_content_id: paigelighton
          media_content_type: routine
