#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# Neato Support for D7 Connected Botvac - control my [Neato Vacuum](https://amzn.to/2kqnnqu) with Home Assistant.
#-------------------------------------------

sensor:
  - platform: alpha_vantage
    scan_interval: 2400
    api_key: !secret vantage_api
    symbols:
      - name: Tesla
        currency: USD
        symbol: TSLA
      - name: VMware
        currency: USD
        symbol: VMW
      - name: Amazon
        currency: USD
        symbol: AMZN

  - platform: coinmarketcap
    currency_id: 1027
  - platform: coinmarketcap
    currency_id: 1
#-------------------------------------------

##############################################################################
###  Automations - Detect when things are not right. Like any Good Watchdog.
##############################################################################
#automation:
#Tweets pushed out to twitter.
