#-------------------------------------------
#  Fire Tablet Alarm Panel -
#  http://www.vmwareinfo.com/2017/07/visualizing-smart-home-using-home.html
#-------------------------------------------
#
homeassistant:
  customize_glob:
    "sensor.*_alarm_panel*":
      hidden: False
    "binary_sensor.*_alarm_panel*":
      hidden: False

media_player:
  - platform: floorplan_speaker
    name: Bedroom Alarm Panel

switch:
  - platform: command_line
    switches:
      bedroom_restart:
        command_on: !secret bedroom_restart_on
        friendly_name: Restart Bedroom Panel
        # This restart switch is called from the Self_heal nightly Automation.

#---Sensors for Fire Tablet-----------------------------

light:

  - platform: mqtt
    name: Bedroom Screensaver
    state_topic: floorplan/bedroom_screensaver
    command_topic: floorplan/bedroom_screensaver/set
    brightness: true

binary_sensor:

  - platform: mqtt
    state_topic: floorplan/bedroom_motion
    name: Bedroom Motion
    device_class: motion
    retain: true
    hidden: False

  - platform: mqtt
    state_topic: floorplan/bedroom_plugged
    name: Bedroom Plugged
    retain: true
    hidden: False
