#-------------------------------------------
# # @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
## Garadget_Stuff -  [Garadget](http://amzn.to/2jQLpVQ) - Garage Door opener/sensor
# Video and Write Up - https://www.vcloudinfo.com/2019/03/how-to-add-garadget-to-home-assistant.html
#-------------------------------------------


cover:
  - platform: garadget
    covers:
        large_garage:
          device: !secret large_garage_id
          username: !secret garadget_username
          password: !secret garadget_password
          name: large_garage
        small_garage:
          device: !secret small_garage_id
          username: !secret garadget_username
          password: !secret garadget_password
          name: small_garage

sensor:
  - platform: template
    sensors:
      small_garage_status:
        friendly_name: 'State of the door'
        entity_id: []
        value_template: '{{ states.cover.small_garage.state }}'
      small_garage_time_in_state:
        friendly_name: 'Time Since Change'
        entity_id: []
        value_template: '{{ states.cover.small_garage.attributes["time_in_state"] }}'
      small_garage_wifi_signal_strength:
        entity_id: []
        friendly_name: 'WiFi strength'
        value_template: '{{ states.cover.small_garage.attributes["wifi_signal_strength"] }}'
        unit_of_measurement: 'dB'
      small_garage_reflection_rate:
        entity_id: []
        friendly_name: 'Reflection Rate'
        value_template: '{{ states.cover.small_garage.attributes["sensor_reflection_rate"] }}'

  - platform: mqtt
    name: 'Small Garage Brightness'
    state_topic: 'garadget/Garadget Small/status'
    unit_of_measurement: '%'
    value_template: '{{ value_json.bright }}'

  - platform: template
    sensors:
      large_garage_status:
        friendly_name: 'State of the door'
        entity_id: []
        value_template: '{{ states.cover.large_garage.state }}'
      large_garage_time_in_state:
        friendly_name: 'Time Since Change'
        entity_id: []
        value_template: '{{ states.cover.large_garage.attributes["time_in_state"] }}'
      large_garage_wifi_signal_strength:
        entity_id: []
        friendly_name: 'WiFi strength'
        value_template: '{{ states.cover.large_garage.attributes["wifi_signal_strength"] }}'
        unit_of_measurement: 'dB'
      large_garage_reflection_rate:
        entity_id: []
        friendly_name: 'Reflection Rate'
        value_template: '{{ states.cover.large_garage.attributes["sensor_reflection_rate"] }}'

  - platform: mqtt
    name: 'Large Garage Brightness'
    state_topic: 'garadget/Garadget Large/status'
    unit_of_measurement: '%'
    value_template: '{{ value_json.bright }}'

group:
  garadget:
    name: Garadget Sensors
    entities:
      - cover.large_garage
      - sensor.large_garage_status
      - sensor.large_garage_time_in_state
      - sensor.large_garage_wifi_signal_strength
      - sensor.large_garage_reflection_rate
      - sensor.large_garage_brightness
      - cover.small_garage
      - sensor.small_garage_status
      - sensor.small_garage_time_in_state
      - sensor.small_garage_wifi_signal_strength
      - sensor.small_garage_reflection_rate
      - sensor.small_garage_brightness
  garage_doors:
    name: Garage Doors
    entities:
      - cover.large_garage
      - cover.small_garage

automation:
  - alias: 'Update Garage Brightness'
    trigger:
      - platform: time_pattern
        minutes: '/5'
    action:
      - service: mqtt.publish
        data:
          topic: "garadget/Garadget Small/command"
          payload: "get-status"
      - service: mqtt.publish
        data:
          topic: "garadget/Garadget Large/command"
          payload: "get-status"
