#-------------------------------------------
#  RSS Podcast Alerting function Packages
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
feedreader:
    urls:
      - https://hasspodcast.io/feed/podcast #HA Podcast Feed
      - https://us12.campaign-archive.com/feed?u=45cab4343ffdbeb9667c28a26&id=e01847e94f #This is CCOSTAN's Smart Home Blog feed
# - http://feeds.feedburner.com/RecentCommitsToBearStoneHA - This is the Repo Commit feed.
#-------------------------------------------

automation:
  - alias: Send notification of RSS feed title when updated
    trigger:
      platform: event
      event_type: feedreader

    action:
      - service: notify.html5
        data_template:
          title: "New RSS Item available"
          message: "New RSS Item - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }} {{trigger.event.data.title}}"
          data:
            url: "{{trigger.event.data.link}}"

      - service: persistent_notification.create
        data_template:
          title: "{{trigger.event.data.title}}"
          message: "New RSS item available - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
          notification_id: "update_available"

############ everything below this line should be deleted if using as a drop in package. ####################

      - service: script.notify_engine
        data_template:
          value1: 'There is a new RSS item available for {{trigger.event.data.title}}.'
          value2: '{{trigger.event.data.link}}'
          who: 'carlo'

      - service: script.tweet_engine_image
        data_template:
          tweet: '{{trigger.event.data.title}} - {{trigger.event.data.link}}'
          image: >-
            {% set pictures = [
              "/config/www/custom_ui/floorplan/images/branding/BearStoneParty.png",
              "/config/www/custom_ui/floorplan/images/branding/Chalk-Podcast.png"
            ] %}
            {{ pictures|random }}
