#-------------------------------------------
#  RSS Podcast Alerting function Packages
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
feedreader:
    urls:
      - https://hasspodcast.io/feed/podcast #HA Podcast Feed
      - https://us12.campaign-archive.com/feed?u=45cab4343ffdbeb9667c28a26&id=e01847e94f #This is CCOSTAN's Smart Home Blog feed
      # - https://feeds.feedburner.com/RecentCommitsToBearStoneHA # - This is the Repo Commit feed.
#-------------------------------------------

automation:
  - alias: Send notification of RSS feed title when updated
    trigger:
      platform: event
      event_type: feedreader

    action:

      - service: script.tweet_engine_image
        data_template:
          tweet: '{{trigger.event.data.title}} - {{trigger.event.data.link}}'
          image: >-
            {% set pictures = [
              "/config/www/custom_ui/floorplan/images/branding/BearStoneParty.png",
              "/config/www/custom_ui/floorplan/images/branding/Chalk-Podcast.png"
            ] %}
            {{ pictures|random }}
