#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# Neato Support for D7 Connected Botvac - control my [Neato Vacuum](https://amzn.to/2kqnnqu) with Home Assistant.
#-------------------------------------------

##############################################################################
###  Automations - Detect when things are not right. Like any Good Watchdog.
##############################################################################
automation:
  - alias: 'Vacuum -Tweet'
    trigger:
      - platform: state
        entity_id: vacuum.carlo_neato
        to: 'cleaning'

    condition:
      - condition: template
        value_template: "{{ states.vacuum.carlo_neato.attributes.battery_level |int < 20 }}"

      - condition: template
        value_template: >
          {%- if states.automation.vacuum_tweet.attributes.last_triggered -%}
            {{ (as_timestamp(now()) - as_timestamp(states.automation.vacuum_tweet.attributes.last_triggered)) > 15000 }}
          {%- else -%}
            true
          {%- endif -%}

    action:
      - service: script.tweet_engine_image
        data_template:
          tweet: >
            {{ [
            "#Neato returning to base. Vacuumed up a TON. (https://amzn.to/2CKHZya)",
            "Everyday I have the Neato Botvac go out and clean the house on its own.",
            "Since we have a cat that sheds all day, we have Neato Vacuum go out daily to clean.",
            "Time to recharge the Neato Vacuum."
            ] | random + " Battery Level:{{states.vacuum.carlo_neato.attributes.battery_level }} #Robots"}}
          image: >-
            {{ [
            "/config/www/custom_ui/floorplan/images/branding/neato.png"
            ] | random }}
