######################################################################################################
# Nest Protect Package
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# - Write up- https://www.vcloudinfo.com/2017/06/psa-check-out-your-smoke-detectors-once.html
######################################################################################################
#-----------------------------------

automation:
  - alias: Nest protect emergency

    trigger:
      platform: state
      entity_id:
        - sensor.hallway_nest_protect_kids_hallway_smoke_status
        - sensor.hallway_nest_protect_kids_hallway_co_status
        - sensor.justins_room_nest_protect_smoke_status
        - sensor.justins_room_nest_protect_co_status
        - sensor.kitchen_nest_protect_smoke_status
        - sensor.kitchen_nest_protect_co_status
        - sensor.master_bedroom_nest_protect_smoke_status
        - sensor.master_bedroom_nest_protect_co_status
        - sensor.master_hallway_nest_protect_smoke_status
        - sensor.master_hallway_nest_protect_co_status
        - sensor.office_nest_protect_smoke_status
        - sensor.office_nest_protect_co_status
        - sensor.paiges_room_nest_protect_paiges_room_smoke_status
        - sensor.paiges_room_nest_protect_paiges_room_co_status
        - sensor.upstairs_bedroom_nest_protect_smoke_status
        - sensor.upstairs_bedroom_nest_protect_co_status
        - sensor.upstairs_living_room_nest_protect_smoke_status
        - sensor.upstairs_living_room_nest_protect_co_status
      to: 'Emergency'

    condition:
      - condition: state
        entity_id: group.family
        state: 'home'

    action:
      - service: script.emergency
        data_template:
          call_garage_open: 1
      - service: script.notify_engine
        data_template:
          value1: "An emergency has been detected on {{ trigger.to_state.attributes.friendly_name }} Please investigate IMMEDIATELY."

      - service: script.tweet_engine_no_image
        data_template:
          tweet: "An emergency has been detected on {{ trigger.to_state.attributes.friendly_name }} @CCostan (https://www.vcloudinfo.com/2017/06/psa-check-out-your-smoke-detectors-once.html)"

  - alias: Nest Protect Offline Notify

    trigger:
      platform: state
      entity_id:
        - binary_sensor.upstairs_living_room_nest_protect_online
        - binary_sensor.hallway_nest_protect_kids_hallway_online
        - binary_sensor.justins_room_nest_protect_online
        - binary_sensor.kitchen_nest_protect_online
        - binary_sensor.master_bedroom_nest_protect_online
        - binary_sensor.master_hallway_nest_protect_online
        - binary_sensor.paiges_room_nest_protect_paiges_room_online
        - binary_sensor.upstairs_bedroom_nest_protect_online
        - binary_sensor.office_nest_protect_online
      from: 'on'

    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.alert_mode

      - service: script.speech_engine
        data_template:
          value1: "The {{ trigger.to_state.attributes.friendly_name }} is now {{ (trigger.to_state.state)|replace('_', ' ') }}.  Please check immediately."

      - service: script.notify_engine
        data_template:
          value1: "The {{ trigger.to_state.attributes.friendly_name }} is now {{ (trigger.to_state.state)|replace('_', ' ') }}.  Please check immediately."
          who: "parents"
          apns_id: 'Nest-Protect'

      - service: script.tweet_engine_no_image
        data:
          tweet: "Oh NO! {{ trigger.to_state.attributes.friendly_name }} is now in {{ (trigger.to_state.state)|replace('_', ' ') }} mode. @Nest. (https://www.vcloudinfo.com/2017/06/psa-check-out-your-smoke-detectors-once.html) #Safety"
