#-------------------------------------------
#  PiHole ad Blocking Related Packages
#-------------------------------------------
# homeassistant:
#   customize:
#
#     sensor.pihole_ads_percentage_today:
#       friendly_name: Percentage of Ad Traffic Blocked
#       unit_of_measurement: '%'
#       icon: mdi:ticket-percent
#
#     group.pihole:
#       homebridge_hidden: true
#-------------------------------------------
sensor:
  - platform: rest
    name: House now
    resource: http://192.168.10.90/api/meters/aggregates
    method: GET
    value_template: '{{ value_json.load.instant_power / 1000 }}'
    unit_of_measurement: kWh

  - platform: rest
    name: Grid now
    resource: http://192.168.10.90/api/meters/aggregates
    method: GET
    value_template: '{{ value_json.site.instant_power / 1000 }}'
    unit_of_measurement: kWh

  - platform: rest
    name: Solar now
    resource: http://192.168.10.90/api/meters/aggregates
    method: GET
    value_template: '{{ value_json.solar.instant_power / 1000 }}'
    unit_of_measurement: kWh

  - platform: rest
    name: PowerWall Battery now
    resource: http://192.168.10.90/api/meters/aggregates
    method: GET
    value_template: '{{ value_json.battery.instant_power / 1000 }}'
    unit_of_measurement: kWh

  - platform: rest
    name: PowerWall Battery Capacity
    resource: http://192.168.10.90/api/system_status/soe
    method: GET
    value_template: '{{ 13500 // (100 / value_json.percentage) }}'
    unit_of_measurement: W

#-------------------------------------------
group:
  Power:
    entities:
      - sensor.powerwall_battery_capacity
      - sensor.powerwall_battery_now
      - sensor.grid_now
      - sensor.house_now
      - sensor.solar_now
      - camera.grafana_solar_graph
#-------------------------------------------

#
# automation:
# Located in the Grafana package.  Tweets out Solar Production Daily!   
