#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# Rachio Sprinkler system Support
#-------------------------------------------
######################################################################
##  [Rachio Sprinkler system](https://amzn.to/2eoPKBW) - Smart Sprinkler controller
######################################################################

sensor:
  - platform: mqtt
    state_topic: "ifttt/rachio/watering_time"
    name: "Rachio_watering_time"

automation:
  ###################################
  ##  LOG IFTTT Stuff - Rachio
  ###################################
  - alias: 'Log Sprinkler Activity'
    id: eab41723-231d-4db6-ab22-d1658665639a

    trigger:
      - platform: event
        #Sent from IFTTT Webhooks : {"action":"IFTTT_Rachio", "water_time":" {{DurationInMinutes}}"}
        event_type: ifttt_webhook_received
        event_data:
          action: IFTTT_Rachio

    action:
      - service: mqtt.publish
        data_template:
          payload: '{{ states("sensor.date") }}'
          topic: 'ifttt/rachio/watering_time'
          retain: true

      - service: script.tweet_engine_image
        data_template:
          tweet: >
            {{ [
            "Just finished watering the lawn with @_Rachio.",
            "The lawn looked thirsty so I watered it.",
            "My lawn looks great and we definately do not water it nearly as much as everyone else. (https://amzn.to/2eoPKBW)",
            "No rain in the forecast? @_Rachio knows & chose to water the lawn.",
            ".@CCostan does not even think about watering the lawn. Me and @_Rachio take care of that.",
            "Unfortunately, my Rachio Sprinkler system has cloud dependancies. Nimbus and Cumulus to be exact! Time to Water!" 
            ] | random + " #SavingWater"}}
          image: >-
            {{ [
            "/config/www/custom_ui/floorplan/images/branding/sprinkler.png",
            "/config/www/custom_ui/floorplan/images/branding/sprinkler2.png",
            "/config/www/custom_ui/floorplan/images/branding/sprinkler3.png"
            ] | random }}
