#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# Neato Support for D7 Connected Botvac - control my [Neato Vacuum](http://amzn.to/2kqnnqu) with Home Assistant.
#-------------------------------------------
######################################################################
##  [Rachio Sprinkler system](http://amzn.to/2eoPKBW) - Smart Sprinkler controller
######################################################################
homeassistant:
  # customize_glob:
  #   "*.carlojuice*":
  #     homebridge_hidden: True
  #     hidden: False
#-------------------------------------------
rachio:
  api_key: !secret rachio_api
