#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# Support for Rheem Water Heaters (https://amzn.to/36yOSnN)
# https://github.com/CCOSTAN/Home-AssistantConfig/issues/892
# https://www.home-assistant.io/integrations/econet/
# No Sensors are added.  Only 2 Services to put the mode in Vacation Mode (and then exit)
#-------------------------------------------

# Moved to UI

# water_heater:
#   - platform: econet
#     username: !secret rheem_username
#     password: !secret rheem_password

##############################################################################
###  Automations
##############################################################################
