#-------------------------------------------
#  SpeedTest Related Packages
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig

speedtestdotnet:
  scan_interval:
    hours: 6
  monitored_conditions:
    - download
    - upload
