#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------
# homeassistant:
#   customize_glob:
#     "sensor.carlo_6*":
#
#     "sensor.staceys_iphone_*":

camera:
  - platform: synology
    url: !secret synology_url
    username: !secret synology_username
    password: !secret synology_password
    timeout: 15
    verify_ssl: False
