#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# More Info : https://www.vcloudinfo.com/
#-------------------------------------------
#-------------------------------------------
#  Clean data for the Floorplan UI.
#-------------------------------------------

#---Sensor for Time and Date.-----------------------------
sensor:
  - platform: template
    scan_interval: 30000
    sensors:
      floorplan_date:
        friendly_name: 'Date'
        value_template: >-
          {{now().strftime("%A")}}, {{now().strftime("%B")}} {{now().strftime("%d")}}

  - platform: template
    scan_interval: 60
    sensors:
      floorplan_time:
        friendly_name: 'Time'
        value_template: >-
          {{now().strftime("%-I")}}:{{now().strftime("%M")}} {{now().strftime("%p")}}
      clock_time:
        friendly_name: 'Clock Time'
        value_template: >-
          {{now().strftime("%-I")}}:{{now().strftime("%M")}}

  - platform: template
    scan_interval: 30000
    sensors:
      clock_am_pm:
        friendly_name: 'AM/PM'
        value_template: >-
          {{now().strftime("%p")}}
      clock_day:
        friendly_name: 'Day'
        value_template: >-
          {{now().strftime("%A")}}
      clock_date:
        friendly_name: 'Clock Date'
        value_template: >-
          {{now().strftime("%B")}} {{now().strftime("%d")}} {{now().year}}
