#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
###################################
## Tuya compatible Devices - https://www.vcloudinfo.com/2018/12/how-to-waterproof-your-outdoor-smart.html
###################################
tplink:
  discovery: true
  switch:
    - host: 192.168.10.116

# homeassistant:
#   customize_glob:
#     "sensor.skybell_*":
#       icon: mdi:camera-front
#
#       hidden: False
#       homebridge_hidden: True

# group:
#   bolt:
#     name: Chevy Bolt EV
#     control: hidden
#     entities:
#       - device_tracker.Carlo_Bolt
#       - binary_sensor.mychevy_plugged_in
#       - sensor.mychevy_charge_mode
#       - sensor.mychevy_charging
#       - sensor.mychevy_evcharge
#       - sensor.mychevy_mileage
#       - sensor.mychevy_range
#       - sensor.mychevy_status
