#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
###################################
## TPink compatible Devices - https://www.vcloudinfo.com/2018/12/how-to-waterproof-your-outdoor-smart.html
###################################
tplink:
  discovery: true
  switch:
    - host: 192.168.10.116
