language: python

python: "3.7"

before_install:
  - touch fake_key.pem
  - mv config/travis_secrets.yaml config/secrets.yaml

install:
  - pip3 install homeassistant
  - pip3 install colorlog
  - pip3 install python-dateutil

script:
  - hass -c config/ --script check_config --info all
