- name: TV Time
  entities:
       light.m1_front_left:
           state: off
       light.m1_front_right:
           state: off
       light.m1_slider:
           state: off
       light.m1_back_right:
           state: on
           rgb_color: &gold [255,223,0]   # Gold
           brightness: 50
       light.m1_back_left:
           state: on
           rgb_color: *gold    # Gold
           brightness: 50
       light.tv_stand_light:
           state: on
           rgb_color: *gold    # Gold
           brightness: 150
       light.tv_light:
           state: on
           rgb_color: *gold    # Gold
           brightness: 150
       light.couch_1:
           state: on
           rgb_color: *gold    # Gold
           brightness: 255

- name: Red_living_Room
  entities:
      light.m1_front_left:
          state: on
          rgb_color: &red [255,0,0]
          brightness: 150
      light.m1_front_right:
          state: on
          rgb_color: *red  # RED
          brightness: 150
      light.m1_back_right:
          state: on
          rgb_color: *red  # RED
          brightness: 150
      light.m1_back_left:
          state: on
          rgb_color: *red  # RED
          brightness: 150
      light.tv_stand_light:
          state: on
          rgb_color: *red  # RED
          brightness: 255
      light.tv_light:
          state: on
          rgb_color: *red  # RED
          brightness: 255
      light.couch_1:
          state: on
          rgb_color: *red  # RED
          brightness: 255
