##########  ############################################################
##  Announce when people come or go.
## Announce over all Chromecast Audios
######################################################################
- alias: 'Guest Mode Audio Feedback'

  trigger:
    - platform: state
      entity_id:
        - input_boolean.guest_mode
      from: 'off'
      to: 'on'

  action:
    - service: script.speech_engine
      data_template:
        value1: >
          {{ [
          "Guest Mode has been enabled for today."
          ] | random }}
        call_responsibilities: 1
        call_no_announcement: 1
        call_garage_check: 1
        call_window_check: 1
