######################################################################
##  Who's day is it anyway? Pretty sure my parent's didn't code to figure this out.
######################################################################
- alias: 'responsibilities'
  id: f39bd8db-a348-4024-a6a6-a3e3c836646c
  trigger:
    - platform: state
      entity_id: input_boolean.responsibilities
      to: 'on'

  action:
    - service: script.speech_engine
      data:
        call_responsibilities: 1
