######################################################################
##  Awesome [Etekcity Outlets](http://amzn.to/2efNoBP) control via RF
### connected to
## [433Mhz Transmitter and receiver](http://amzn.to/2dceNY2)
## Migrated to http://amzn.to/2DJPfdl
######################################################################

- platform: tplink
  name: Living_Room_Amp
  host: 192.168.10.116

# Thanks to @ZOMBU2 for providing me with the right firmware - http://cn-fwversions.ibroadlink.com/firmware/download/10026/20028.bin
- platform: broadlink
  host: 192.168.10.118
  mac: '34:EA:34:CC:CE:25'
  switches:
    kitchen_accents:
      friendly_name: "Kitchen Accents"
      command_on: 'sjcyAAcSBxMHEgcSBxIUBgcTBxIIEhMGBxITBggSFAYHEhQGBxIHExQGFAYIEwcSFAYTBge8AAAAAAAA'
      command_off: 'stgyAAcTBxMHEwcSBxMTBgcTBxMHExMHBxMUBgcTEwcHExMHBxMHExMHEwcTBxMHBxMHEwe9AAAAAAAA'

    kitchen_accents_2:
      friendly_name: "Kitchen Accents 2"
      command_on: 'sjcyAAcSBxMHEgcSBxIUBgcTBxIIEhMGBxITBggSFAYHEhQGBxIHExQGFAYIEwcSFAYTBge8AAAAAAAA'
      command_off: 'stgyAAcTBxMHEwcSBxMTBgcTBxMHExMHBxMUBgcTEwcHExMHBxMHExMHEwcTBxMHBxMHEwe9AAAAAAAA'

    den_outlet:
      friendly_name: "Den Outlet"
      command_on: 'sjgyAAgSEwYHEhQGBxIIEgcSFAYHEhMGBxIUBgcSFAYUBhMGBxMHEggSBxIHEgcSFAYUBge+AAAAAAAA'
      command_off: 'slUyAAcSFAYHEhQGBxMHEgcTFAYHEhQGBxIUBgcSFAYTBhMHBxIHEwcSBxMTBhMHBxMHEwe+AAAAAAAA'

    foyer_outlet:
      friendly_name: "Foyer Outlet"
      command_on: 'sh8yAAcSBxMHEwcTBxIUBgcTBxMHExMGEwcTBwcTFAYHExMHBxMHEwcSBxMHEgcSEwcTBge9AAAAAAAA'
      command_off: 'skIyAAcTBxIHEgcSBxMTBgcTBxIHExQGEwYUBgcTEwcHExQGBxMHEgcTBxITBxMGBxMHEge8AAAAAAAA'

    living_room_outlet:
      friendly_name: "Living Room Outlet"
      command_on: 'slYyAAcTEwcHExMHBxMGEwcTEwcHExMHBxMTBwYTEwcHExMHEwcTBwcTBxMHEwcTEwcTBwe+AAAAAAAA'
      command_off: 'sl4yAAcTEwcGExMHBxMHEwcTFAcHExMHBxMTBwYTEwcHExMHEwcTBwYTBxMTBxMHBhMHEwe+AAAAAAAA'

    master_bathroom_accents:
      friendly_name: "Master Bathroom Accents"
      command_on: 'siAyAAUTEQcFExEIBhMGEwYTBhMGExEHBhMRCAYTEQgGExEHBRMFExEIEQgGEwYTEQcRBwa1AAAAAAAA'
      command_off: 'sjsyAAYSEgcGEhIHBhIGEgYTBhMGExIHBhIRBwYSEQcGExIHBhIGEhIHEQcSBxEHBhIGEga0AAAAAAAA'

    1412_2_outlet:
      friendly_name: "1412_2 Outlet"
      command_on: 'sjYyAAYSEgcGEhEHBhIGEgYSBhMGEhIHBhISBwYSEgcGEhIHEgcSBwYSBhIGEwYSEgcRBwa0AAAAAAAA'
      command_off: 'siwyAAYSEQcGExEHBhIGEwYTBhMGExEHBhMRBwYTEQcGExEHEQcRBwYSBhMSBxEHBhIGEwa1AAAAAAAA'

    1412_3_outlet:
      friendly_name: "1412_3 Outlet"
      command_on: 'siUyAAYSEgcGEhIHBhIGEgYSBhIGEhIHBhISBwYSEgYSBxIHBhIGEgYSBhIGEgYSEgcSBwa0AAAAAAAA'
      command_off: 'smMyAAcSEgcGExIHBhIHEgcSBhIGEhIHBhISBgcSEgcSBxIHBxIGEgcSBhISBxIHBhIGEge0AAAAAAAA'

    printer_outlet:
      friendly_name: "Printer Outlet"
      command_on: 'shkyAAcSBxIHEwcSBxITBgcSBxMHExMGBxITBgcTEwcTBxMGBxMHEgcTBxMHEgcSEwYTBge7AAAAAAAA'
      command_off: 'slEyAAcTBxMHEwcSBxMTBwcTBxMHExMGBxMTBwcTEwcTBxMHBxMHEwcTBxMTBxMHBxMHEge7AAAAAAAA'

    front_door_outlet:
      friendly_name: "Front Door Outlet"
      command_on: 'skYyAAcTBxMHEgcSBxMTBgcSBxIHExMHBxMTBxMHEwYHEhMGBxIHEgcTBxIHEgcSEwYTBge7AAAAAAAA'
      command_off: 'sjwyAAcTBxIHEwcTBxMTBwcTBxIHExMGBxMTBhMGEwYHEhMGBxMHEwcTBxMTBxMGBxMGEwe7AAAAAAAA'

    garage_outlet:
      friendly_name: "Garage Outlet"
      command_on: 'sioyAAYTEwcHExMHBxMHEwcTEwcHExMHBxMTBxMHEwcHExMHBxMGEwcTBxMHEwYTEwcTBwe/AAAAAAAA'
      command_off: 'smQyAAcTEwcHExMHBxMGEwcTEwcHExMHBxMTBxMHEwcHExMHBhMGEwcTBhMTBxMHBxMGEwe/AAAAAAAA'

# - platform: rpi_rf
#   gpio: 17
#   switches:
# # Outlet 1412_1 - ALSO Controls # Outlet 304_1
#     master_bathroom_accents:
#       protocol: 1
#       pulselength: 186
#       code_on: 5264691
#       code_off: 5264700
#       signal_repetitions: 40
#
# # Outlet 304_1 Controlled by Outlet 1412_1
#     master_bathroom_accents_2:
#       protocol: 1
#       pulselength: 186
#       code_on: 5330227
#       code_off: 5330236
#       signal_repetitions: 40
#
#   # Outlet 1412_3
# #    Living_Room_Amp:
#     1412_3_outlet:
#       protocol: 1
#       pulselength: 186
#       code_on: 5265155
#       code_off: 5265164
#       signal_repetitions: 40
#
# # Outlet 1412_2
#     1412_2_outlet:
#       protocol: 1
#       pulselength: 186
#       code_on: 5264835
#       code_off: 5264844
#       signal_repetitions: 40
#
# # # Outlet 311_5
# #     Foyer_outlet:
# #       protocol: 1
# #       pulselength: 186
# #       code_on: 292099
# #       code_off: 292108
# #       signal_repetitions: 40
#
# # # Outlet 311_1
# #     Kitchen_Accents:
# #       protocol: 1
# #       pulselength: 186
# #       code_on: 283955
# #       code_off: 283964
# #       signal_repetitions: 40
# #
# # # Outlet 311_2 : Responds to 311_1 as well.
# #     Kitchen_Accent_2:
# #       protocol: 1
# #       pulselength: 186
# #       code_on: 284099
# #       code_off: 284108
# #       signal_repetitions: 40
#
# # Outlet 311_3
#     Printer_outlet:
#       protocol: 1
#       pulselength: 186
#       code_on: 284419
#       code_off: 284428
#       signal_repetitions: 40
#
# # Outlet 311_4
#     Front_Door_outlet:
#       protocol: 1
#       pulselength: 186
#       code_on: 285955
#       code_off: 285964
#       signal_repetitions: 50
#
# # Outlet 304_2
#     Living_Room_outlet:
#       protocol: 1
#       pulselength: 186
#       code_on: 5330371
#       code_off: 5330380
#       signal_repetitions: 40
#
# # # Outlet 304_3
# #     Den_outlet:
# #       protocol: 1
# #       pulselength: 186
# #       code_on: 5330691
# #       code_off: 5330700
# #       signal_repetitions: 50
#
# # Outlet_304_4
#     Garage_outlet:
#       protocol: 1
#       pulselength: 186
#       code_on: 5332227
#       code_off: 5332236
#       signal_repetitions: 40
