###################################################
## Various MQTT sensors
###################################################

- platform: mqtt
  state_topic: "ifttt/rachio/watering_time"
  name: "Rachio_watering_time"

- platform: mqtt
  state_topic: "dash/medicine/medicine_time"
  name: "Medicine time"
