##############################################################################
###  Detect when things are on and forgotten about. Like any Good Watchdog.
##############################################################################

- alias: Automated Light WatchDog!
  id: 57a921ca-6009-46e7-9ba6-699eee6cf733
  trigger:
    - platform: state
      entity_id:
        - light.hallway
        - light.hallway_lights
        - light.foyer_lights
      to: 'on'
      for: '00:20:00'

    - platform: state
      entity_id:
        - light.upstairs_lights
      to: 'on'
      for: '02:00:00'

#Turn it off!
  action:
    - service: homeassistant.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"

- alias: Make it Right WatchDog!
  id: ddd4397e-951f-46f2-9362-3bff2caa9cf3
  trigger:
    - platform: time_pattern
      minutes: '/15'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'

#Turn it off!
  action:
    - service: homeassistant.turn_off
      data_template:
        entity_id:
          - switch.front_landscaping
          - switch.back_landscaping
          - light.outdoor_foyer
          - light.outdoor_sconce_1
          - light.outdoor_sconce_2
          - light.outdoor_sconce_3
          - light.led_garage_large
          - light.led_garage_snip
          - light.led_garage_small
          - light.led_outdoor_den
          - light.outdoor_bathroom
          - light.flood2
