binary_sensor.bedroom_alarm_panel:
  friendly_name: 'Bedroom Alarm Panel'
  
  hidden: False
  homebridge_hidden: true




binary_sensor.carlowink:
  friendly_name: 'Carlo-Wink'
  
  hidden: False
  homebridge_hidden: True
  icon: mdi:router-wireless



binary_sensor.downstairs_thermostat_fan:
  friendly_name: 'Downstairs Thermostat Fan'
  
  hidden: True
  homebridge_hidden: True




binary_sensor.downstairs_thermostat_has_leaf:
  friendly_name: 'Downstairs Thermostat Has Leaf'
  
  hidden: True
  homebridge_hidden: True




binary_sensor.downstairs_thermostat_is_locked:
  friendly_name: 'Downstairs Thermostat Is Locked'
  
  hidden: True
  homebridge_hidden: True




binary_sensor.downstairs_thermostat_is_using_emergency_heat:
  friendly_name: 'Downstairs Thermostat Is Using Emergency Heat'
  
  hidden: True
  homebridge_hidden: True




binary_sensor.downstairs_thermostat_online:
  friendly_name: 'Downstairs Thermostat Online'
  
  hidden: True
  homebridge_hidden: True




binary_sensor.entry_alarm_panel:
  friendly_name: 'Entry Alarm Panel'
  
  hidden: False
  homebridge_hidden: true




binary_sensor.hallway_linen:
  friendly_name: 'Hallway Linen Door'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:home-variant



binary_sensor.hallway_nest_protect_kids_hallway_online:
  friendly_name: 'Kids Hallway Protect'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:nest-protect



binary_sensor.hallway_pantry:
  friendly_name: 'Hallway Pantry Door'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:home-variant



binary_sensor.iss:
  friendly_name: 'Iss Visibility'
  
  hidden: False
  homebridge_hidden: True
  icon: mdi:satellite-variant



binary_sensor.justins_room_nest_protect_online:
  friendly_name: 'Justins Room Protect'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:nest-protect



binary_sensor.kitchen_door:
  friendly_name: 'Kitchen Door'
  
  hidden: False
  homebridge_hidden: False
  icon: mdi:home-variant



binary_sensor.kitchen_nest_protect_online:
  friendly_name: 'Kitchen Protect'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:nest-protect



binary_sensor.master_bedroom_nest_protect_online:
  friendly_name: 'Master Bedroom Protect'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:nest-protect



binary_sensor.master_hallway_nest_protect_online:
  friendly_name: 'Master Hallway Protect'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:nest-protect



binary_sensor.mcu1_gpio10:
  friendly_name: 'Dining Room Windows'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:security-home



binary_sensor.mcu1_gpio12:
  friendly_name: 'Interior Garage Door'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:security-home



binary_sensor.mcu1_gpio13:
  friendly_name: 'Front Den Windows'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:security-home



binary_sensor.mcu1_gpio14:
  friendly_name: 'Office Window'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:security-home



binary_sensor.mcu1_gpio4:
  friendly_name: 'Paige Window'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:security-home



binary_sensor.mcu1_gpio5:
  friendly_name: 'Front Door'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:security-home



binary_sensor.mcu2_gpio10:
  friendly_name: 'Master Bathroom Window'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:security-home



binary_sensor.mcu2_gpio12:
  friendly_name: 'Main Slider'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:security-home



binary_sensor.mcu2_gpio13:
  friendly_name: 'Upstairs Bedroom Window'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:security-home



binary_sensor.mcu2_gpio14:
  friendly_name: 'Justin Window'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:security-home



binary_sensor.mcu2_gpio4:
  friendly_name: 'Dinette Windows'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:security-home



binary_sensor.mcu2_gpio5:
  friendly_name: 'Back Door'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:security-home



binary_sensor.mcu2_gpio9:
  friendly_name: 'Master Slider'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:security-home



binary_sensor.mcu3_gpio10:
  friendly_name: 'Master Bedroom Window'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:security-home



binary_sensor.mcu3_gpio14:
  friendly_name: 'Upstairs Windows'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:security-home



binary_sensor.mcu3_gpio4:
  friendly_name: 'Stacey Bedroom Window'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:security-home



binary_sensor.mcu3_gpio5:
  friendly_name: 'Carlo Bedroom Window'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:security-home



binary_sensor.mcu3_light:
  friendly_name: 'Panel Door'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:security-home



binary_sensor.office_motion:
  friendly_name: 'Office Motion Sensor'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:sensor



binary_sensor.office_nest_protect_online:
  friendly_name: 'Office Protect'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:nest-protect



binary_sensor.paiges_room_nest_protect_paiges_room_online:
  friendly_name: 'Paiges Room Protect'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:nest-protect



binary_sensor.sleepnumber_carlo_carlo_is_in_bed:
  friendly_name: 'Carlo Is In Bed'
  
  hidden: False
  homebridge_hidden: False




binary_sensor.sleepnumber_carlo_stacey_is_in_bed:
  friendly_name: 'Stacey Is In Bed'
  
  hidden: False
  homebridge_hidden: False




binary_sensor.upstairs_bedroom_nest_protect_online:
  friendly_name: 'Upstairs Bedroom Protect'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:nest-protect



binary_sensor.upstairs_living_room_nest_protect_online:
  friendly_name: 'Upstairs Living Room Protect'
  
  hidden: False
  homebridge_hidden: true
  icon: mdi:nest-protect



binary_sensor.upstairs_thermostat_fan:
  friendly_name: 'Upstairs Thermostat Fan'
  
  hidden: True
  homebridge_hidden: True




binary_sensor.upstairs_thermostat_has_leaf:
  friendly_name: 'Upstairs Thermostat Has Leaf'
  
  hidden: True
  homebridge_hidden: True




binary_sensor.upstairs_thermostat_is_locked:
  friendly_name: 'Upstairs Thermostat Is Locked'
  
  hidden: True
  homebridge_hidden: True




binary_sensor.upstairs_thermostat_is_using_emergency_heat:
  friendly_name: 'Upstairs Thermostat Is Using Emergency Heat'
  
  hidden: True
  homebridge_hidden: True




binary_sensor.upstairs_thermostat_online:
  friendly_name: 'Upstairs Thermostat Online'
  
  hidden: True
  homebridge_hidden: True
