device_tracker.actiontechap:
  friendly_name: 'Actiontechap'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.bedroom_alarm_panel:
  friendly_name: 'Bedroom Alarm Panel'
  
  hidden: True
  homebridge_hidden: True

device_tracker.hue_hub_1:
  friendly_name: 'Hue Hub 1'
  
  hidden: True
  homebridge_hidden: True

device_tracker.hue_hub_2:
  friendly_name: 'Hue Hub 2'
  
  hidden: True
  homebridge_hidden: True

device_tracker.entry_alarm_panel:
  friendly_name: 'Entry Alarm Panel'
  
  hidden: True
  homebridge_hidden: True




device_tracker.alexa_echo:
  friendly_name: 'Alexa Echo'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.amazon_dot:
  friendly_name: 'Amazon Dot'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.amazon_fire_stick:
  friendly_name: '50f5da4cd5ec'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.carlo:
  friendly_name: 'Carlo'
  
  hidden: False
  homebridge_hidden: True
  icon: False



device_tracker.carlopihole:
  friendly_name: 'Carlo-Pihole'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.chromecast_audio_1:
  friendly_name: 'Chromecast Audio 1'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.chromecast_audio_2:
  friendly_name: 'Chromecast Audio 2'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.circle:
  friendly_name: 'Circle'
  
  hidden: True
  homebridge_hidden: True
  icon: False

device_tracker.study_ap:
  friendly_name: 'Ubiquiti AP Study'
  
  hidden: True
  homebridge_hidden: True
  icon: False

device_tracker.cisco_ap:
  friendly_name: 'Cisco Ap'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.hue_h_1:
  friendly_name: 'Hue H 1'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.hue_h_2:
  friendly_name: 'Hue H 2'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.ipmdemounit:
  friendly_name: 'Ipmdemounit'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.justin_dot:
  friendly_name: 'Justin-Dot'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.large_garage:
  friendly_name: 'Large Garage'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.living_room_roku:
  friendly_name: 'Living Room Roku'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.master_bedroom_roku:
  friendly_name: 'Master Bedroom Roku'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.nest_downstairs:
  friendly_name: 'Nest Downstairs'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.nest_upstairs:
  friendly_name: 'Nest Upstairs'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.nodemcu1:
  friendly_name: 'Nodemcu1'
  
  hidden: True
  homebridge_hidden: True
  icon: mdi:chip



device_tracker.nodemcu2:
  friendly_name: 'Nodemcu2'
  
  hidden: True
  homebridge_hidden: True
  icon: mdi:chip



device_tracker.nodemcu3:
  friendly_name: 'Nodemcu3'
  
  hidden: True
  homebridge_hidden: True
  icon: mdi:chip



device_tracker.nodemcu4:
  friendly_name: 'A020a618077f'
  
  hidden: True
  homebridge_hidden: True
  icon: mdi:chip



device_tracker.printer:
  friendly_name: '001ba94e7b4a'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.rachio:
  friendly_name: 'Rachio'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.rgb_led_garage_large:
  friendly_name: 'Rgb Led Garage Large'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.rgb_led_garage_small:
  friendly_name: 'Rgb Led Garage Small'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.rgb_led_outdoor_den:
  friendly_name: 'Rgb Led Outdoor Den'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.samsungtv:
  friendly_name: 'Samsung Tv'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.skybell:
  friendly_name: 'Skybell'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.sleep_number_bed:
  friendly_name: 'Sleep Number Bed'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.small_garage:
  friendly_name: 'Small Garage'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.smart_water_meter:
  friendly_name: 'Smart Water Meter'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.stacey:
  friendly_name: 'Stacey'
  
  hidden: False
  homebridge_hidden: True
  icon: False



device_tracker.staceyiphone_nat:
  friendly_name: 'Stacey Iphone 2'
  
  hidden: True
  homebridge_hidden: true




device_tracker.tablotv:
  friendly_name: 'Tablotv'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.trendnetap:
  friendly_name: 'Trendnet Ap'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.unifi_ap:
  friendly_name: 'Unifi Ap'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.wii:
  friendly_name: 'Wii'
  
  hidden: True
  homebridge_hidden: True
  icon: False



device_tracker.withings_scale:
  friendly_name: 'Withings Scale'
  
  hidden: True
  homebridge_hidden: True
  icon: False
