group.all_automations:
  friendly_name: 'All Automations'
  
  hidden: True
  homebridge_hidden: true


group.all_covers:
  friendly_name: 'All Covers'
  
  hidden: True
  homebridge_hidden: true


group.all_devices:
  friendly_name: 'All Devices'
  
  hidden: True
  homebridge_hidden: true


group.all_lights:
  friendly_name: 'All Lights'
  
  hidden: True



group.all_scripts:
  friendly_name: 'All Scripts'
  
  hidden: True
  homebridge_hidden: true

group.all_switches:
  friendly_name: 'All Switches'
  
  hidden: True



group.amps:
  friendly_name: 'Amps'
  
  hidden: False
  homebridge_hidden: true


group.sleep_number_bed:
  friendly_name: 'Sleep Number Bed'
  
  hidden: False
  homebridge_hidden: true


group.bedroom_lights:
  friendly_name: 'Bedroom Lights'
  
  hidden: False



group.den_lights:
  friendly_name: 'Den Lights'
  
  hidden: False



group.dinette_lights:
  friendly_name: 'Dinette Lights'
  
  hidden: False



group.dining_room_lights:
  friendly_name: 'Dining Room Lights'
  
  hidden: False



group.exterior_lights:
  friendly_name: 'Exterior Lights'
  
  hidden: False



group.family:
  friendly_name: 'Family'
  
  hidden: False
  homebridge_hidden: true


group.foyer_lights:
  friendly_name: 'Foyer Lights'
  
  hidden: False



group.garage_doors:
  friendly_name: 'Garage Doors'
  
  hidden: False
  homebridge_hidden: true


group.garage_lights:
  friendly_name: 'Garage Lights'
  
  hidden: False



group.hallway_lights:
  friendly_name: 'Hallway Lights'
  
  hidden: False



group.home_modes:
  friendly_name: 'Home Modes'
  
  hidden: False
  homebridge_hidden: true


group.interior_lights:
  friendly_name: 'Interior Lights'
  
  hidden: False



group.justins_room:
  friendly_name: 'Justins Room'
  
  hidden: False



group.kitchen_lights:
  friendly_name: 'Kitchen Lights'
  
  hidden: False



group.living_room_accents:
  friendly_name: 'Living Room Accents'
  
  hidden: False



group.living_room_lights:
  friendly_name: 'Living Room Lights'
  
  hidden: False



group.media_players:
  friendly_name: 'Media Players'
  
  hidden: False
  homebridge_hidden: true


group.network:
  friendly_name: 'Network'
  
  hidden: False
  homebridge_hidden: true


group.office_lights:
  friendly_name: 'Office Lights'
  
  hidden: False



group.outdoor_front_lights:
  friendly_name: 'Outdoor Front Lights'
  
  hidden: False



group.outdoor_pool_lights:
  friendly_name: 'Outdoor Pool Lights'
  
  hidden: False



group.paiges_room:
  friendly_name: 'Paiges Room'
  
  hidden: False



group.sensors:
  friendly_name: 'Sensors'
  
  hidden: False
  homebridge_hidden: true


group.switches:
  friendly_name: 'Switches'
  
  hidden: False
  homebridge_hidden: true


group.upstairs_lights:
  friendly_name: 'Upstairs Lights'
  
  hidden: False



group.weather:
  friendly_name: 'Weather'
  
  hidden: False
  homebridge_hidden: true
