input_boolean.alert_mode:
  friendly_name: 'Alert Mode'
  
  hidden: False

  icon: mdi:alert-octagram



input_boolean.color_tornado:
  friendly_name: 'Color Tornado'
  
  hidden: False

  icon: mdi:invert-colors



input_boolean.daylight_override:
  friendly_name: 'Daylight Override'
  
  hidden: False





input_boolean.flash:
  friendly_name: 'Flash'
  
  hidden: False

  icon: mdi:yin-yang



input_boolean.good_morning:
  friendly_name: 'Good Morning'
  
  hidden: False

  icon: mdi:weather-sunset-up



input_boolean.good_night:
  friendly_name: 'Good Night'
  
  hidden: False

  icon: mdi:weather-night



input_boolean.guard_dog:
  friendly_name: 'Guard Dog'
  
  hidden: False

  icon: mdi:paw



input_boolean.guest_mode:
  friendly_name: 'Guest Mode'
  
  hidden: False

  icon: mdi:account-alert



input_boolean.home_stats:
  friendly_name: 'Home Stats'
  
  hidden: False

  icon: mdi:chart-bar



input_boolean.house_station:
  friendly_name: 'House Station'
  
  hidden: False

  icon: mdi:radio



input_boolean.lastmsg:
  friendly_name: 'Repeat Message'
  
  hidden: False

  icon: mdi:repeat-once



input_boolean.meal_time:
  friendly_name: 'Meal Time'
  
  hidden: False

  icon: mdi:food



input_boolean.medicine:
  friendly_name: 'Medicine'
  
  hidden: False





input_boolean.responsibilities:
  friendly_name: 'Responsibilities'
  
  hidden: False

  icon: mdi:delete-sweep



input_boolean.school_mode:
  friendly_name: 'School Mode'
  
  hidden: False

  icon: mdi:school



input_boolean.self_destruct:
  friendly_name: 'Self Destruct'
  
  hidden: False

  icon: mdi:skull



input_boolean.sleepy_dog:
  friendly_name: 'Sleepy Dog'
  
  hidden: False

  icon: mdi:bell-sleep



input_boolean.speech_notifications:
  friendly_name: 'Speech Notifications'
  
  hidden: False

  icon: mdi:speaker-wireless



input_boolean.tv_time:
  friendly_name: 'Tv Time'
  
  hidden: False

  icon: mdi:television-guide



input_boolean.work:
  friendly_name: 'Work'
  
  hidden: False

  icon: mdi:briefcase
