light.bedroom:
  friendly_name: 'Bedroom'
  
  hidden: False
  homebridge_hidden: True




light.bedroom_hallway:
  friendly_name: 'Bedroom Hallway'
  
  hidden: False
  homebridge_hidden: True




light.couch_1:
  friendly_name: 'Couch 1'
  
  hidden: False
  homebridge_hidden: True




light.d1:
  friendly_name: 'D1'
  
  hidden: False
  homebridge_hidden: True




light.d2:
  friendly_name: 'D2'
  
  hidden: False
  homebridge_hidden: True




light.den_lamp:
  friendly_name: 'Den Lamp'
  
  hidden: False
  homebridge_hidden: True




light.f1:
  friendly_name: 'F1'
  
  hidden: False
  homebridge_hidden: True




light.f2:
  friendly_name: 'F2'
  
  hidden: False
  homebridge_hidden: True




light.fridge:
  friendly_name: 'Fridge'
  
  hidden: False
  homebridge_hidden: True




light.garage_attic:
  friendly_name: 'Garage Attic'
  
  hidden: False
  homebridge_hidden: true




light.justin_go:
  friendly_name: 'Justin Go'
  
  hidden: False
  homebridge_hidden: True




light.k1:
  friendly_name: 'K1'
  
  hidden: False
  homebridge_hidden: True




light.k2:
  friendly_name: 'K2'
  
  hidden: False
  homebridge_hidden: True




light.k3:
  friendly_name: 'K3'
  
  hidden: False
  homebridge_hidden: True




light.k4:
  friendly_name: 'K4'
  
  hidden: False
  homebridge_hidden: True




light.k5:
  friendly_name: 'K5'
  
  hidden: False
  homebridge_hidden: True




light.k6:
  friendly_name: 'K6'
  
  hidden: False
  homebridge_hidden: True




light.kids_hallway:
  friendly_name: 'Kids Hallway'
  
  hidden: False
  homebridge_hidden: True




light.led_garage_large:
  friendly_name: 'Garage Large Led'
  
  hidden: False
  homebridge_hidden: True

light.led_garage_snip:
  friendly_name: 'Garage Snip Led'
  
  hidden: False
  homebridge_hidden: True


light.led_garage_small:
  friendly_name: 'Garage Small Led'
  
  hidden: False
  homebridge_hidden: True




light.led_outdoor_den:
  friendly_name: 'Outdoor Den Led'
  
  hidden: False
  homebridge_hidden: True




light.m1_back_left:
  friendly_name: 'M1 Back Left'
  
  hidden: False
  homebridge_hidden: True




light.m1_back_right:
  friendly_name: 'M1 Back Right'
  
  hidden: False
  homebridge_hidden: True




light.m1_front_left:
  friendly_name: 'M1 Front Left'
  
  hidden: False
  homebridge_hidden: True




light.m1_front_right:
  friendly_name: 'M1 Front Right'
  
  hidden: False
  homebridge_hidden: True




light.m1_slider:
  friendly_name: 'M1 Slider'
  
  hidden: False
  homebridge_hidden: True




light.master_toilet:
  friendly_name: 'Master Toilet'
  
  hidden: False
  homebridge_hidden: True




light.office_lamp:
  friendly_name: 'Office Lamp'
  
  hidden: False
  homebridge_hidden: False




light.outdoor_bathroom:
  friendly_name: 'Outdoor Bathroom'
  
  hidden: False
  homebridge_hidden: True




light.outdoor_foyer:
  friendly_name: 'Outdoor Foyer'
  
  hidden: False
  homebridge_hidden: True




light.outdoor_sconce_1:
  friendly_name: 'Outdoor Sconce 1'
  
  hidden: False
  homebridge_hidden: True




light.outdoor_sconce_2:
  friendly_name: 'Outdoor Sconce 2'
  
  hidden: False
  homebridge_hidden: True




light.outdoor_sconce_3:
  friendly_name: 'Outdoor Sconce 3'
  
  hidden: False
  homebridge_hidden: True




light.outside_pool_lights:
  friendly_name: 'Outside Pool Lights'
  
  hidden: False
  homebridge_hidden: true




light.p1_back_left:
  friendly_name: 'P1 Back Left'
  
  hidden: False
  homebridge_hidden: True




light.p1_back_right:
  friendly_name: 'P1 Back Right'
  
  hidden: False
  homebridge_hidden: True




light.p1_front_left:
  friendly_name: 'P1 Front Left'
  
  hidden: False
  homebridge_hidden: True




light.p1_front_right:
  friendly_name: 'P1 Front Right'
  
  hidden: False
  homebridge_hidden: True




light.paige_go:
  friendly_name: 'Paige Go'
  
  hidden: False
  homebridge_hidden: True




light.s1:
  friendly_name: 'S1'
  
  hidden: False
  homebridge_hidden: True




light.s2:
  friendly_name: 'S2'
  
  hidden: False
  homebridge_hidden: True




light.s3:
  friendly_name: 'S3'
  
  hidden: False
  homebridge_hidden: True




light.s4:
  friendly_name: 'S4'
  
  hidden: False
  homebridge_hidden: True




light.sink:
  friendly_name: 'Sink'
  
  hidden: False
  homebridge_hidden: True




light.tv_light:
  friendly_name: 'Tv Light'
  
  hidden: False
  homebridge_hidden: True




light.tv_stand_light:
  friendly_name: 'Tv Stand Light'
  
  hidden: False
  homebridge_hidden: True




light.upstairs_lamp:
  friendly_name: 'Upstairs Lamp'
  
  hidden: False
  homebridge_hidden: True
