light.bedroom:
  friendly_name: 'Bedroom'
  
  hidden: False





light.bedroom_hallway:
  friendly_name: 'Bedroom Hallway'
  
  hidden: False





light.couch_1:
  friendly_name: 'Couch 1'
  
  hidden: False





light.d1:
  friendly_name: 'D1'
  
  hidden: False





light.d2:
  friendly_name: 'D2'
  
  hidden: False





light.den_lamp:
  friendly_name: 'Den Lamp'
  
  hidden: False





light.f1:
  friendly_name: 'F1'
  
  hidden: False





light.f2:
  friendly_name: 'F2'
  
  hidden: False





light.fridge:
  friendly_name: 'Fridge'
  
  hidden: False





light.garage_attic:
  friendly_name: 'Garage Attic'
  
  hidden: False





light.justin_go:
  friendly_name: 'Justin Go'
  
  hidden: False





light.k1:
  friendly_name: 'K1'
  
  hidden: False





light.k2:
  friendly_name: 'K2'
  
  hidden: False





light.k3:
  friendly_name: 'K3'
  
  hidden: False





light.k4:
  friendly_name: 'K4'
  
  hidden: False





light.k5:
  friendly_name: 'K5'
  
  hidden: False





light.k6:
  friendly_name: 'K6'
  
  hidden: False





light.kids_hallway:
  friendly_name: 'Kids Hallway'
  
  hidden: False





light.led_garage_large:
  friendly_name: 'Garage Large Led'
  
  hidden: False


light.led_garage_snip:
  friendly_name: 'Garage Snip Led'
  
  hidden: False



light.led_garage_small:
  friendly_name: 'Garage Small Led'
  
  hidden: False





light.led_outdoor_den:
  friendly_name: 'Outdoor Den Led'
  
  hidden: False





light.m1_back_left:
  friendly_name: 'M1 Back Left'
  
  hidden: False





light.m1_back_right:
  friendly_name: 'M1 Back Right'
  
  hidden: False





light.m1_front_left:
  friendly_name: 'M1 Front Left'
  
  hidden: False





light.m1_front_right:
  friendly_name: 'M1 Front Right'
  
  hidden: False





light.m1_slider:
  friendly_name: 'M1 Slider'
  
  hidden: False





light.master_toilet:
  friendly_name: 'Master Toilet'
  
  hidden: False





light.office_lamp:
  friendly_name: 'Office Lamp'
  
  hidden: False
  




light.outdoor_bathroom:
  friendly_name: 'Outdoor Bathroom'
  
  hidden: False





light.outdoor_foyer:
  friendly_name: 'Outdoor Foyer'
  
  hidden: False





light.outdoor_sconce_1:
  friendly_name: 'Outdoor Sconce 1'
  
  hidden: False





light.outdoor_sconce_2:
  friendly_name: 'Outdoor Sconce 2'
  
  hidden: False





light.outdoor_sconce_3:
  friendly_name: 'Outdoor Sconce 3'
  
  hidden: False





light.outside_pool_lights:
  friendly_name: 'Outside Pool Lights'
  
  hidden: False





light.p1_back_left:
  friendly_name: 'P1 Back Left'
  
  hidden: False





light.p1_back_right:
  friendly_name: 'P1 Back Right'
  
  hidden: False





light.p1_front_left:
  friendly_name: 'P1 Front Left'
  
  hidden: False





light.p1_front_right:
  friendly_name: 'P1 Front Right'
  
  hidden: False





light.paige_go:
  friendly_name: 'Paige Go'
  
  hidden: False





light.s1:
  friendly_name: 'S1'
  
  hidden: False





light.s2:
  friendly_name: 'S2'
  
  hidden: False





light.s3:
  friendly_name: 'S3'
  
  hidden: False





light.s4:
  friendly_name: 'S4'
  
  hidden: False





light.sink:
  friendly_name: 'Sink'
  
  hidden: False





light.tv_light:
  friendly_name: 'Tv Light'
  
  hidden: False





light.tv_stand_light:
  friendly_name: 'Tv Stand Light'
  
  hidden: False





light.upstairs_lamp:
  friendly_name: 'Upstairs Lamp'
  
  hidden: False

