scene.all_off:
  friendly_name: 'All Off'
  
  hidden: False




scene.front_full_brightness:
  friendly_name: 'Front Full Brightness'
  
  hidden: False

scene.month_fathers_day_colors:
  friendly_name: 'Fathers Day Colors'
  
  hidden: True


scene.month_cinco_de_mayo_colors:
  friendly_name: 'Month Cinco De Mayo Colors'
  
  hidden: True




scene.month_easter_colors:
  friendly_name: 'Month Easter Colors'
  
  hidden: True




scene.month_mardi_gras_colors:
  friendly_name: 'Month mardi Gras Colors'
  
  hidden: True




scene.month_rwb_colors:
  friendly_name: 'Month Rwb Colors'
  
  hidden: True




scene.month_st_patty_colors:
  friendly_name: 'Month St Patty Colors'
  
  hidden: True




scene.month_standard_colors:
  friendly_name: 'Month Standard Colors'
  
  hidden: True




scene.month_valentine_colors:
  friendly_name: 'Month Valentine Colors'
  
  hidden: True




scene.tv_time:
  friendly_name: 'Tv Time'
  
  hidden: False
