###################################
##  Switches Section
###################################
switch.den_outlet:
  friendly_name: 'Den Outlet'
  
  hidden: False
  icon: mdi:power-plug
  assumed_state: true


switch.foyer_outlet:
  friendly_name: 'Foyer Outlet'
  
  hidden: False
  icon: mdi:power-plug
  assumed_state: true


switch.front_door_outlet:
  friendly_name: 'Front Door Outlet'
  
  hidden: False
  icon: mdi:power-plug
  assumed_state: true

switch.garage_outlet:
  friendly_name: 'Garage Outlet'
  
  hidden: False
  icon: mdi:power-plug
  assumed_state: true

switch.landscaping:
  friendly_name: 'Landscaping Lights'
  
  hidden: True
  homebridge_hidden: True

switch.back_landscaping:
  friendly_name: 'Back Landscaping'
  
  hidden: False
  homebridge_hidden: false
  icon: mdi:flower


switch.front_landscaping:
  friendly_name: 'Front Landscaping'
  
  hidden: False
  homebridge_hidden: False
  icon: mdi:flower

switch.pool_deck:
  friendly_name: 'Pool Deck'
  
  hidden: False
  homebridge_hidden: False

switch.kitchen_accent_2:
  friendly_name: 'Kitchen Accents 2'
  
  hidden: False
  icon: mdi:lightbulb-outline
  assumed_state: true


switch.kitchen_accents:
  friendly_name: 'Kitchen Accents'
  
  hidden: False
  icon: mdi:lightbulb-outline
  assumed_state: true


switch.living_room_amp:
  friendly_name: 'Living Room Amp'
  
  hidden: False
  icon: mdi:music-circle

switch.living_room_outlet:
  friendly_name: 'Living Room Outlet'
  
  hidden: False
  icon: mdi:power-plug
  assumed_state: true


switch.master_bathroom_accents:
  friendly_name: 'Master Bathroom Accents'
  
  hidden: False
  icon: mdi:lightbulb-outline
  assumed_state: true


switch.outlet_304_2:
  friendly_name: 'Outlet 304 2'
  
  hidden: False
  icon: mdi:power-plug
  assumed_state: true

switch.printer_outlet:
  friendly_name: 'Printer Outlet'
  
  hidden: False
  icon: mdi:printer
  assumed_state: true

switch.pihole_temp_disable:
  friendly_name: 'Pihole Temp Disable'
  
  hidden: False
  homebridge_hidden: true
