###################################
##  Switches Section
###################################


switch.pool_deck:
  friendly_name: 'Pool Deck'

  hidden: False
  


switch.lr_amp:
  friendly_name: 'Living Room Amp'

  hidden: False
  icon: mdi:music-circle


switch.pihole_temp_disable:
  friendly_name: 'Pihole Temp Disable'

  hidden: False

