
###################################
##  Nest Section
###################################
climate.downstairs:
  friendly_name: 'Nest Downstairs'
  icon: mdi:air-conditioner
climate.upstairs:
  friendly_name: 'Nest Upstairs'
  icon: mdi:air-conditioner

  
###################################
##  Sun Section
###################################
sun.sun:
  hidden: true
  