
###################################
##  Nest Section
###################################
climate.downstairs:
  friendly_name: 'Nest Downstairs'
  icon: mdi:air-conditioner
climate.upstairs:
  friendly_name: 'Nest Upstairs'
  icon: mdi:air-conditioner
sensor.downstairs_nest_eta:
  hidden: True
sensor.upstairs_nest_eta:
  hidden: True

###################################
##  Sun Section
###################################
sun.sun:
  hidden: true
