######################################################################
##  Color Tornado!
######################################################################
- alias: 'Color Tornado'
  id: f6e89034-b3e6-4951-9cea-7d7053b30857
  trigger:
    - platform: state
      entity_id: input_boolean.color_tornado
      to: 'on'
      from: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.justin_go
      data:
        effect: colorloop

    - service: light.turn_on
      entity_id:
        - light.justin_go
      data:
        effect: colorloop

    - service: input_boolean.turn_off
      entity_id: input_boolean.color_tornado
