######################################################################
##  Good night Routine
######################################################################

- alias: 'Good Night Trigger'
  trigger:
    - platform: state
      entity_id: input_boolean.good_night
      to: 'on'
      from: 'off'
    - platform: state
      entity_id:
        - binary_sensor.sleepnumber_carlo_carlo_is_in_bed
        - binary_sensor.sleepnumber_carlo_stacey_is_in_bed
      to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.sleepnumber_carlo_carlo_is_in_bed
          state: 'on'
        - condition: state
          entity_id: device_tracker.carlo
          state: 'not_home'
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.sleepnumber_carlo_stacey_is_in_bed
          state: 'on'
        - condition: state
          entity_id: device_tracker.stacey
          state: 'not_home'

  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.good_night

    - service: script.speech_engine
      data_template:
        value1: >
          {{ [
          "Sleep Tight, Don't let the bedbugs bite.",
          "Have pleasant dreams",
          "As they say in the Navy, See you in the rise."
          "Dream pleasant dreams.  Tomorrow is a new day.",
          "Early sleep and early wake up gives health and makes you grow.",
          "Good night, good night! Parting is such sweet sorrow that I shall say goodnight till it is Morrow.",
          "There is a time for many words, and there is also a time for sleep.",
          "This good night isn’t meant to bring an end to this day. It’s intended to wish you awesomeness in what lies ahead.",
          "Stuff your worries in your pillow, wrap your troubles in your blanket and spread your anxieties on your sheets. When you wake up tomorrow, you may have dirty linen, but more importantly, you’ll have a fresh mind and a happy heart. Good night.",
          "Goodnight, talk to you tomorrow. ",
          "Goodnight sweetheart. ",
          "Go to bed, you sleepy head! ",
          "Nighty Night. ",
          "Sleep snug as a bug in a rug! ",
          "Lights out! ... Uh huh. ... Dance, dance dance. ",
          "Time to ride the rainbow to dreamland! ",
          "Sweet dreams. ",
          "See ya' in the mornin'! ",
          "I-ill be right here when you wake up. moo ahh .. ha .. ha ",
          "I-ill be dreaming of your face! ",
          "You're the most wonderful user in the whole world! ",
          "I'm yours, forever and always. ",
          "Parting is such sweet sorrow, that I shall say good night till it be tomorrow. ",
          "Can you hear that? ... Its your soft warm bed calling your name. You really must go and see what it wants. ",
          "Grumpy cat says goodnight.",
          "Goodnight, sweet dreams. ",
          "You have so much to be greatful for... goodnight.",
          "Wishing you a goodnight and sweatest dreams.",
          "What about good night kisses? "
          ] | random }}
    - service: script.interior_off
