###################################
##  IFTTT checks Office 365 Calendar and Notifies me of appointments. Flash lights but only at reasonable hours.
###################################
- alias: 'IFTTT Appointment reminder'
  id: 271d2fa0-4dfa-4af2-90de-3f61ff94a420

  trigger:
    - platform: event
      #Sent from IFTTT Webhooks : {"action":"IFTTT_Appointment:}
      event_type: ifttt_webhook_received
      event_data:
        action: IFTTT_Appointment


  condition:
    - condition: time
      after: '08:00:00'
      before: '20:00:00'

  action:
    - service: script.flash_notify
