###################################
##  IFTTT checks Office 365 Calendar and Notifies me of appointments. Flash lights but only at reasonable hours.
###################################
- alias: 'IFTTT Appointment reminder'
  hide_entity: True
  trigger:
    - platform: event
      event_type: IFTTT_Appointment
  
  condition:
    - condition: time
      after: '06:00:00'
      before: '20:00:00'
  
  action:
    - service: script.flash_notify
  

