######################################################################
##  Time to work - Set it up!
######################################################################

- alias: Time to Work
  id: 5ccdc0c7-5a90-4d0d-b3dd-d855fa6cf77d
  trigger:
    - platform: state
      entity_id: input_boolean.work
      to: 'on'
      from: 'off'

  action:
    - service: light.turn_off
      entity_id:
        - light.dinette_lights
        - light.kitchen_lights
        - light.living_room_lights
    - service: light.turn_on
      entity_id:
        - light.office_lamp
    - service: input_boolean.turn_off
      entity_id: input_boolean.work
