homeassistant:
  name: Bear Stone
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  customize_domain:
    automation:
      initial_state: 'on'
  customize_glob:
    automation.*watchdog*:
      icon: mdi:timer
    sensor.dark_sky_*:
      homebridge_hidden: true
    scene.month_*_colors:
      hidden: true
      homebridge_hidden: true
  packages: !include_dir_named packages
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
   - type: trusted_networks

#Note: The influxdb runs along side the HA DB.  It does not replace it.  influxdb is used to grab data for Grafana.
influxdb:
  host: 192.168.10.10
  database: home_assistant

config:
cloud:
  alexa:
    filter:
      include_entities:
        - group.all_lights
        - group.all_switches
        - group.interior_lights
        - group.bedroom_lights
        - group.living_room_lights
        - group.living_room_accents
        - group.dinette_lights
        - group.dining_room_lights
        - group.den_lights
        - group.foyer_lights
        - group.office_lights
        - group.hallway_lights
        - group.kitchen_lights
        - group.upstairs_lights
        - group.outdoor_pool_lights
        - group.garage_lights
        - group.paiges_room
        - group.justins_room
        - group.Exterior_Lights
        - group.outdoor_pool_lights
        - group.outdoor_front_lights
        - group.landscaping
      include_domains:
        - switch
        - cover
        - input_boolean
      # exclude_entities:
      # exclude_domains:
      #   - light
      #   - media_player
    entity_config:
      group.kitchen_lights:
        display_categories: LIGHT
      group.bedroom_lights:
        display_categories: LIGHT
      group.upstairs_lights:
        display_categories: LIGHT
http:
  base_url: !secret http_base_url
  # server_port: !secret http_port
  api_password: !secret http_api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  trusted_networks:
    - 192.168.10.0/24
    - !secret external_ip
  ip_ban_enabled: True
  login_attempts_threshold: 3

frontend:
  javascript_version: latest

panel_custom:
  - name: floorplan
    sidebar_title: Alarm Panel
    sidebar_icon: mdi:security-home
    url_path: floorplan
    config:
      hide_app_toolbar:
      config: /local/custom_ui/floorplan/floorplan.yaml

  - name: clock
    sidebar_title: Alarm Clock
    sidebar_icon: mdi:alarm
    url_path: clock
    config:
      hide_app_toolbar:
      config: /local/custom_ui/floorplan/floorclock.yaml

discovery:
  ignore:
    - samsung_tv
#   - roku
#   - google_cast

updater:
  include_used_components: true

sun:
hue:
  bridges:
    - host: 192.168.10.75
      filename: phue.conf
      allow_unreachable: true
      allow_hue_groups: false

    - host: 192.168.10.76
      filename: phue2.conf
      allow_unreachable: true
      allow_hue_groups: false

light:
  # Reference : https://www.flexfireleds.com/pages/Comparison-between-3528-LEDs-and-5050-LEDs.html
  - platform: flux_led
    automatic_add: True
    devices:
      192.168.10.30:
        name: led_garage_snip
        mode: "rgb"
      192.168.10.31:
        name: led_outdoor_den
        mode: "rgb"
      192.168.10.32:
        name: led_garage_large
        mode: "rgb"
      192.168.10.33:
        name: led_garage_small
        mode: "rgb"

# emulated_hue:
#   host_ip: 192.168.10.10
#   listen_port: 8300
#   expose_by_default: false

ifttt:
  key: !secret ifttt_key

logbook:
  exclude:
    entities:
      - automation.detect_lights_and_adjust_the_brightness_when_turned_on_based_on_time
      - automation.cuckoo_clock
      - binary_sensor.office_motion
      - group.garage_doors
      - media_player.LivingRoomCC
      - py.warnings
      - sensor.last_boot
      - sensor.last_boot_templated
      - sensor.small_garage_status
      - sensor.large_garage_status
      - sensor.small_garage_time_in_state
      - sensor.large_garage_time_in_state
      - sensor.large_garage_wifi_signal_strength
      - sensor.small_garage_wifi_signal_strength
      - sensor.small_garage_reflection_rate
      - sensor.large_garage_reflection_rate
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_today
      - sensor.time
      - sensor.date
      - sensor.floorplan_date
      - sensor.floorplan_time
      - sensor.ha_uptime

history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
      - binary_sensor
      - cover

  exclude:
    entities:
     - sensor.last_boot
     - sensor.date
     - sensor.pihole_ads_blocked_today
     - sensor.pihole_ads_percentage_blocked_today
     - sensor.pihole_dns_queries_today
     - sensor.last_boot
     - sensor.last_boot_templated
     - sensor.floorplan_date
     - sensor.floorplan_time
     - sensor.ha_uptime
     - sensor.time

logger: !include logger.yaml
recorder: !include recorder.yaml

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-Carlo
  username: !secret MQTT_username
  password: !secret MQTT_password

# zwave:
#  usb_path: /dev/ttyACM0
#  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

climate:
  platform: nest

# media_player:
#   - platform: cast
#     host: 192.168.10.209 #CCA1
#   - platform: roku

  # - platform: samsungtv
  #   host: 192.168.10.207
  #   port: 8001
  #   name: Living Room TV
  #   scan_interval: 180

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_ID
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: 'us-east-1'
    text_type: ssml
    cache: True
   # cache_dir: /data/tts

wink:
  # email: !secret wink_username
  # password: !secret wink_password
  # local_control: True

group: !include_dir_merge_named group
device_tracker: !include_dir_merge_list device_tracker
sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
switch: !include_dir_merge_list switch
script: !include_dir_merge_named script
input_boolean: !include_dir_merge_named input_boolean
shell_command: !include_dir_merge_named shell_command
