climate.downstairs:
  config_entry_id: dff91f79d9df415d8788eaf512325435
  name:
  platform: nest
  unique_id: fn9dKY_tWE2bMKuCEsb-64cJSplFTogF
climate.upstairs:
  config_entry_id: dff91f79d9df415d8788eaf512325435
  name:
  platform: nest
  unique_id: IGN9FBW-V-uQdnhd222ZW4cJSplFTogF
sensor.carlojuice_charge_time:
  config_entry_id:
  name:
  platform: juicenet
  unique_id: 0817010902030429879317243104-charge_time
sensor.carlojuice_energy_added:
  config_entry_id:
  name:
  platform: juicenet
  unique_id: 0817010902030429879317243104-energy_added
sensor.carlojuice_amps:
  config_entry_id:
  name:
  platform: juicenet
  unique_id: 0817010902030429879317243104-amps
sensor.carlojuice_watts:
  config_entry_id:
  name:
  platform: juicenet
  unique_id: 0817010902030429879317243104-watts
sensor.carlojuice_voltage:
  config_entry_id:
  name:
  platform: juicenet
  unique_id: 0817010902030429879317243104-voltage
sensor.carlojuice_charging_status:
  config_entry_id:
  name:
  platform: juicenet
  unique_id: 0817010902030429879317243104-status
sensor.carlojuice_temperature:
  config_entry_id:
  name:
  platform: juicenet
  unique_id: 0817010902030429879317243104-temperature
sensor.carlo_6s_battery_state:
  config_entry_id:
  name:
  platform: ios
  unique_id: state_carlo_6s
sensor.carlo_6s_battery_level:
  config_entry_id:
  name:
  platform: ios
  unique_id: level_carlo_6s
sensor.staceys_iphone_battery_level:
  config_entry_id:
  name:
  platform: ios
  unique_id: level_staceys_iphone
sensor.staceys_iphone_battery_state:
  config_entry_id:
  name:
  platform: ios
  unique_id: state_staceys_iphone
light.justin_go:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 00:17:88:01:01:15:54:3c-0b
light.d2:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:10:e6:a4-01
light.outdoor_bathroom:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:16:f4:3b-01
light.paige_go:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 00:17:88:01:01:14:f8:fe-0b
light.k2:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:04:19:c3-01
light.k4:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:02:db:d2-01
light.tv_light:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 00:17:88:01:01:1b:e7:78-0b
light.couch_1:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 00:17:88:01:01:1b:96:08-0b
light.m1_slider:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:01:91:96-01
light.bedroom_hallway:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:13:79:f9-01
light.kids_hallway:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:07:36:2e-01
light.garage_attic:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:13:f0:3e-01
light.k5:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:05:3a:78-01
light.bedroom:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:11:a8:56-01
light.d1:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:14:01:b6-01
light.m1_back_right:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:01:b7:6b-01
light.tv_stand_light:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 00:17:88:01:01:1b:96:0f-0b
light.m1_front_right:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:05:3a:cc-01
light.m1_back_left:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:05:23:09-01
light.k3:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:06:16:3a-01
light.m1_front_left:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:05:4a:30-01
light.k1:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:01:74:65-01
light.sink:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:07:64:12-01
light.office_lamp:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:12:66:0a-01
light.fridge:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:07:97:c7-01
light.k6:
  config_entry_id: 7e9bfa52b2d04ebe82893e4043bf944b
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:05:82:ee-01
light.outdoor_foyer:
  config_entry_id: 97428cbb507e4afcbe38eb8b9c4f2732
  name:
  platform: hue
  unique_id: 00:17:88:01:02:6f:af:67-0b
light.upstairs_lamp:
  config_entry_id: 97428cbb507e4afcbe38eb8b9c4f2732
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:02:be:e3-01
light.outdoor_sconce_1:
  config_entry_id: 97428cbb507e4afcbe38eb8b9c4f2732
  name:
  platform: hue
  unique_id: 00:17:88:01:10:25:b0:3b-0b
light.den_lamp:
  config_entry_id: 97428cbb507e4afcbe38eb8b9c4f2732
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:13:39:e9-01
light.s1:
  config_entry_id: 97428cbb507e4afcbe38eb8b9c4f2732
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:04:44:f7-01
light.f1:
  config_entry_id: 97428cbb507e4afcbe38eb8b9c4f2732
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:02:fb:1b-01
light.s2:
  config_entry_id: 97428cbb507e4afcbe38eb8b9c4f2732
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:07:94:11-01
light.s3:
  config_entry_id: 97428cbb507e4afcbe38eb8b9c4f2732
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:06:64:bd-01
light.f2:
  config_entry_id: 97428cbb507e4afcbe38eb8b9c4f2732
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:06:14:91-01
light.outdoor_sconce_2:
  config_entry_id: 97428cbb507e4afcbe38eb8b9c4f2732
  name:
  platform: hue
  unique_id: 00:17:88:01:10:4a:ed:01-0b
light.upstairs_hallway:
  config_entry_id:
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:12:b3:ff-01
light.outdoor_sconce_3:
  config_entry_id: 97428cbb507e4afcbe38eb8b9c4f2732
  name:
  platform: hue
  unique_id: 00:17:88:01:10:25:a0:7f-0b
light.s4:
  config_entry_id: 97428cbb507e4afcbe38eb8b9c4f2732
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:04:5e:6f-01
light.dimmable_light_2:
  config_entry_id: 97428cbb507e4afcbe38eb8b9c4f2732
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:06:50:b0-01
light.dimmable_light_3:
  config_entry_id: 97428cbb507e4afcbe38eb8b9c4f2732
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:02:4b:10-01
light.dimmable_light_1:
  config_entry_id: 97428cbb507e4afcbe38eb8b9c4f2732
  name:
  platform: hue
  unique_id: 7c:e5:24:00:00:04:2f:81-01
media_player.livingroomcc:
  config_entry_id:
  name:
  platform: cast
  unique_id: 243eeafb-51e4-b47a-1d33-ff04819177d5
media_player.whole_house:
  config_entry_id: 41c7cbc168f542e88ec8e6a3e37e20fc
  name:
  platform: cast
  unique_id: 19f3beef-0562-4a1a-bcaf-5b62c4e4757c
media_player.living_room_ultra:
  config_entry_id:
  name:
  platform: roku
  unique_id: YJ00H8674998
media_player.upstairs_living_room:
  config_entry_id:
  name:
  platform: roku
  unique_id: 1GS3AC111661
media_player.master_bedroom:
  config_entry_id:
  name:
  platform: roku
  unique_id: 2N006T621680
