#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# Read all about this and more at https://vCloudInfo.com
# HomeKit control file.
######################################################################################################
# auto_start: false
filter:
  include_domains:
    - climate
    - cover
    - lock
  exclude_domains:
    - media_player
    - sensor
    - script
    - sensor
    - switch
    - scene
    - light
  # include_entities:

  # exclude_entities:
