#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# Read all about this and more at https://vCloudInfo.com
# HomeKit control file.
######################################################################################################
# auto_start: false
filter:
  include_domains:
    - climate
    - cover
    - lock
    - camera
  exclude_domains:
    - media_player
    - sensor
    - script
    - sensor
    - switch
    - scene
    - light
  include_entities:
    - camera.camera1
    - camera.camera2
    - camera.camera3
    - camera.front_door
    - light.bedroom
    - light.bedroom_lights
    - light.den_lights
    - light.dinette_lights
    - light.dining_room_lights
    - light.foyer_lights
    - light.garage_lights
    - light.hallway_lights
    - light.kitchen_lights
    - light.living_room_accents
    - light.living_room_lights
    - light.office_lights
    - light.outdoor_front_lights
    - light.outdoor_pool_lights
    - light.upstairs_lights
    - switch.lr_amp
  # exclude_entities:
