############################################################
# recorder
############################################################
#db_url: sqlite:///data/home-assistant_v2.db
purge_interval: 1
purge_keep_days: 30
include:
  entities:
    - group.landscaping
exclude:
  domains:
    - updater
    - automation
    - device_tracker
    - group
    - scene
    - script
  entities:
    - binary_sensor.camera1_motion_sensor
    - binary_sensor.camera2_motion_sensor
    - binary_sensor.camera3_motion_sensor
    - sensor.clock_am_pm
    - sensor.clock_date
    - sensor.clock_day
    - sensor.clock_stacey_alarm_time
    - sensor.clock_time
    - sensor.date
    - sensor.external_ip
    - sensor.floorplan_date
    - sensor.floorplan_time
    - sensor.ha_uptime
    - sensor.large_garage_reflection_rate
    - sensor.large_garage_time_in_state
    - sensor.last_message
    - sensor.low_battery
    - sensor.medicine_time
    - sensor.network
    - sensor.network_detail
    - sensor.pihole_ads_blocked_today
    - sensor.pihole_ads_percentage_blocked_today
    - sensor.pihole_dns_queries_today
    - sensor.last_boot
    - sensor.last_boot_templated
    - sensor.skybell_stone_door_chime_level
    - sensor.small_garage_reflection_rate
    - sensor.small_garage_time_in_state
    - sensor.time
    - sensor.rachio_watering_time
    - sun.sun
    - zone.home
