homeassistant_latitude: 000.0000000
homeassistant_longitude: 000.0000000
homeassistant_elevation: 00
http_api_password: password
http_port: 80
external_ip: 10.10.10.10
server_port: 8123
MQTT_username: MQTT_username
MQTT_password: password
ssl_certificate: fake_key.pem
ssl_key: fake_key.pem
http_base_url: vCloudInfo.com
alexa_email: carlo@vCloudInfo.COM
alexa_password: YOUTUBE_vCloudInfo
ifttt_key: iftttKEYPassphrase
camera1_url: http://192.168.10.21:88/cgi-bin/CGIProxy.fcgi?cmd=getDevState&usr=admin&pwd=password
camera2_url: http://192.168.10.22:88/cgi-bin/CGIProxy.fcgi?cmd=getDevState&usr=admin&pwd=password
camera3_url: http://192.168.10.23:88/cgi-bin/CGIProxy.fcgi?cmd=getDevState&usr=admin&pwd=password
forecast_key: ForcastKeyphrase
fitbit_user: User@email.com
fitbit_password: abcdefghijklmnopqrstuvwxyz0123456789
juicenet_access_token: abcdefghijklmnopqrstuvwxyz0123456789
bedroom_restart_on: "/usr/bin/curl -k 'http://192.168.10.127:2323/?cmd=restartApp&password=SecretPassWord'"
nest_client_id: secret_nest_client_id
nest_client_secret: secretnestclientid
neato_username: user@email.com
neato_password: password
mychevy_email: user@email.com
mychevy_password: password
large_garage_id: 00000000000000000000000
small_garage_id: 00000000000000000000001
garadget_username: user@email.com
garadget_password: password
google_cal_clientid: clientidsecretsecretsecret.apps.googleusercontent.com
google_cal_clientsecret: more-secretstuff
sleepiq_username: user@email.com
sleepiq_password: password
synology_url: https://192.168.1.1:5001
synology_username: USERNAME
synology_password: SuperAwesomePassword1
aws_access_key_ID: 'AWSACCESSKEYID'
aws_secret_access_key: 'AWSACCESSKEYIDandSECRET'
unifi_username: username
unifi_password: password
unifi_host: host.domain.local
myusps_username: username
myusps_password: password
upsmychoice_username: username
upsmychoice_password: password
wink_username: user@email.com
wink_password: password
uv_mate_key: 933ecdfb-BurnBabyBurn-8237j2d
uv_mate_resource: https://uvimate.herokuapp.com/api/getUVI/82.6341/-83.0211
rachio_api: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
skybell_username: user@email.com
skybell_password: password
travis_api: THISisTheMostSecureAPIKeyEva
tuya_username: username@me.com
tuya_password: vCloudInfoPassword
twitter_consumer_key: LotsOfNumbers
twitter_consumer_secret: LotsOfLetters
twitter_access_token: Access-to-BearStoneHA
twitter_access_token_secret: AtBearStoneHASecretAccessTokenCode
twitter_consumer_key2: LotsOfNumbers
twitter_consumer_secret2: LotsOfLetters
twitter_access_token2: Access-to-BearStoneHA
twitter_access_token_secret2: AtBearStoneHASecretAccessTokenCode
cloud_client_id: 'SuperSecretCode'
cloud_user_pool: 'SuperSecretPlace'
cloud_relayer: 'SuperSecretWebThingy'
vantage_api: LONGAPIKEYFORFREE
minecraft: private_server.com
