doors:
  name: Doors
  entities:
    - binary_sensor.hallway_linen_opened
    - binary_sensor.hallway_pantry_opened
    - binary_sensor.kitchen_door_opened
    - binary_sensor.MCU2_GPIO12 # Main Slider
    - binary_sensor.MCU3_Light  # Alarm Door
