home_modes:
  control: hidden
  entities:
    - input_boolean.guest_mode
    - input_boolean.school_mode
    - input_boolean.alert_mode
    - input_boolean.speech_notifications
    - input_boolean.text_notifications
    - input_boolean.last_message
    - sensor.low_battery
