Bedroom lights:
  entities:
    - light.bedroom

kitchen lights:
  entities:
    - light.k1
    - light.k2
    - light.k3
    - light.k4
    - light.k5
    - light.k6
    - light.sink
    - light.fridge

Living Room lights:
  entities:
    - light.m1_back_left
    - light.m1_back_right
    - light.m1_front_left
    - light.m1_front_right
    - light.m1_slider

Living Room Accents:
  entities:
    - light.couch_1
    - light.tv_light
    - light.tv_stand_light

Dinette lights:
  entities:
    - light.d1
    - light.d2

Den lights:
  entities:
    - light.den_lamp

Foyer lights:
  entities:
    - light.f1
    - light.f2

Office lights:
  entities:
    - light.office_lamp

Upstairs lights:
  entities:
    - light.upstairs_lamp
    - light.dimmable_light_1
    - light.dimmable_light_2
    - light.upstairs_hallway

Dining Room lights:
  entities:
    - light.s1
    - light.s2
    - light.s3
    - light.s4

Outdoor Pool Lights:
  entities:
    - light.p1_front_left
    - light.p1_front_right
    - light.p1_back_left
    - light.p1_back_right

Outdoor Front Lights:
  entities:
    - light.outdoor_foyer
    - light.outdoor_sconce_1
    - light.outdoor_sconce_2
    - light.outdoor_sconce_3
    - light.led_garage_large
    - light.led_garage_snip
    - light.led_garage_small
    - light.led_outdoor_den
    - light.stone_door

Garage lights:
  control: hidden
  entities:
    - light.garage_attic
    - switch.garage_outlet

Hallway Lights:
  entities:
    - light.kids_hallway
    - light.bedroom_hallway
    - light.upstairs_hallway
    - light.garage_hallway

Justins Room:
  entities:
    - light.justin_go

Paiges Room:
  entities:
    - light.paige_go
