media_players:
  entities:
    - media_player.livingroomcc
    - media_player.living_room_tv
    - media_player.living_room_ultra
    - media_player.upstairs_living_room
    - media_player.bedroom_alarm_panel
    - media_player.living_room
    - media_player.office
    - media_player.kitchen
    - media_player.justin_room
    - media_player.tap
    - media_player.upstairs
