Interior Switches:
  entities:
    - switch.kitchen_accent_1
    - switch.kitchen_accent_2
    - switch.front_door_outlet
    - switch.lr_amp
    - switch.master_bathroom_accent_1
    - switch.master_bathroom_accent_2
    - switch.pool_deck

Kitchen Accents:
  entities:
    - switch.kitchen_accent_1
    - switch.kitchen_accent_2

Master Bathroom Accents:
  entities:
    - switch.master_bathroom_accent_1
    - switch.master_bathroom_accent_2
