Interior Switches:
  entities:
    - switch.den_outlet
    - switch.living_room_outlet
    - switch.foyer_outlet
    - group.kitchen_accents
    - switch.printer_outlet
    - switch.front_door_outlet
    - switch.garage_outlet
    - switch.lr_amp
    - group.master_bathroom_accents
    - switch.pool_deck
    - switch.1412_2_Outlet
    - switch.1412_3_Outlet

kitchen_accents:
  entities:
    - switch.kitchen_accent_1
    - switch.kitchen_accent_2

master_bathroom_accents:
  entities:
    - switch.master_bathroom_accent_1
    - switch.master_bathroom_accent_2
