Triggers:
  control: hidden
  entities:
    - input_boolean.house_station
    - input_boolean.responsibilities
    - input_boolean.home_stats
    - input_boolean.flash
    - input_boolean.guard_dog
    - input_boolean.sleepy_dog
    - input_boolean.good_morning
    - input_boolean.good_night
    - input_boolean.meal_time
    - input_boolean.tv_time
    - input_boolean.work
