######################################################################################################
###[SkyBell HD](http://amzn.to/2dcexIB) Script to turn on Front light FULL bright for 5 to 20m when motion is detected and then return to the normal colors.
#  action:
#   - service: script.front_house_motion
#
######################################################################################################

front_house_motion:
  sequence:
    - service: logbook.log
      data:
        name: "SkyBell HD Doorbell:"
        message: "Someone is by the door."

    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

    - service: input_boolean.turn_on
      entity_id: input_boolean.alert_mode

    - service: script.speech_engine
      data:
        value1: 'Motion has been detected by the front door.'
    - service: scene.turn_on
      entity_id: scene.front_full_brightness
    - service: switch.turn_on
      entity_id:
        - switch.back_landscaping
        - switch.front_landscaping
    - service: light.turn_on
      data:
        entity_id:
          - light.outdoor_bathroom
          - group.outdoor_pool_lights
        brightness: 255
    - service: script.dog_bark
    - delay: '00:{{ range(0,1) | random | int }}{{ range(0,9) | random | int }}:00'
    - service: light.turn_off
      entity_id:
        - group.outdoor_front_lights
        - group.outdoor_pool_lights
    - service: light.turn_on
      entity_id: light.outdoor_bathroom
      data:
        brightness: 15
    - delay: '00:00:10'
    - service: script.monthly_color_scene
